/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 burjkhalifa.glb 
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-burj-khalifa-dubai-c1d6f5884c9c4a56b8d8f9c5555f1902
Title: ( FREE ) Burj Khalifa Dubai
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ConsoleModel(props) {
  const { nodes, materials } = useGLTF('/burjkhalifa.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.142}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Vitres} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Rebord} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Rebord} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Rebord} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Rebord} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Rebord} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Rebord} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Rebord} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Rebord} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Rebord} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Rebord} />
      </group>
    </group>
  )
}

useGLTF.preload('/burjkhalifa.glb')
